kind = "web"
previewPath = "/"
title = "SENSOTECH - Smart Farming"
version = "1.0.0"
id = "artifacts/sensotech"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26012

[services.development]
run = "pnpm --filter @workspace/sensotech run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sensotech", "run", "build" ]
publicDir = "artifacts/sensotech/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26012"
BASE_PATH = "/"
